//Leader Key
#define LEADER_PER_KEY_TIMING
#define LEADER_TIMEOUT 1500
//#define DEBUG_MATRIX_SCAN_RATE
#define VERBOSE_DEBUG 1

//for VIA
// #define EEPROM_SIZE 4096
// #define DYNAMIC_KEYMAP_EEPROM_MAX_ADDR 2047


#ifdef AUDIO_ENABLE
    #define AUDIO_PIN GP7
    #define AUDIO_PWM_DRIVER PWMD3
    #define AUDIO_PWM_CHANNEL RP2040_PWM_CHANNEL_B
    #define AUDIO_INIT_DELAY 50
    //#define STARTUP_SONG SONG(NO_SOUND)
    #define AUDIO_CLICKY
    #define NO_MUSIC_MODE
    #define SENDSTRING_BELL
    // ARM Audio Volume
    //#define AUDIO_DAC_SAMPLE_MAX 4095U
#endif


//Display OLED SSD1306

#define OLED_BRIGHTNESS 128
#define OLED_IC OLED_IC_SSD1306
#define OLED_SCROLL_TIMEOUT 0
#define OLED_TIMEOUT 1800000
// settings for the oled 128x64 0.96
#define OLED_DISPLAY_128X64
#define REAL_OLED_DISPLAY_WIDTH 128
#define REAL_OLED_DISPLAY_HEIGHT 64
#define REAL_OLED_COLUMN_OFFSET (28 - OLED_COLUMN_OFFSET)
#define REAL_OLED_CURSOL_COL_OFFSET (REAL_OLED_COLUMN_OFFSET / OLED_FONT_WIDTH)
#define OLED_UPDATE_INTERVAL 100

// RP2040 I2C I2C0
// settings for 0.96" OLED display
#define I2C_DRIVER I2CD1
#define I2C1_SDA_PIN GP26  //GP28
#define I2C1_SCL_PIN GP27  //GP29

//#define UNICODE_SELECTED_MODES UNICODE_MODE_WINDOWS

#define WS2812_DI_PIN GP16
#define RP_DMA_PRIORITY_WS2812 0
#define WS2812_RP_DMA_CHANNEL 11U
// #define WS2812_PIO_USE_PIO1

// #define BACKLIGHT_PIN GP16
// #define BACKLIGHT_PWM_DRIVER PWMD0
// #define BACKLIGHT_PWM_CHANNEL RP2040_PWM_CHANNEL_A

//#define NOP_FUDGE 1
#ifdef WS2812_DI_PIN
    # define RGBLIGHT_LAYERS
    # define RGBLIGHT_LED_COUNT 1
    # define RGBLIGHT_HUE_STEP 8
    # define RGBLIGHT_SAT_STEP 8
    # define RGBLIGHT_VAL_STEP 8
    # define RGBLIGHT_LIMIT_VAL 255
    # define RGBLIGHT_SLEEP
    // /*== all animations enable ==*/
    #define RGBLIGHT_ANIMATIONS
    // #define RGBLIGHT_EFFECT_BREATHING
    #define RGBLIGHT_EFFECT_RGB_TEST
    #define RGBLIGHT_EFFECT_RAINBOW_MOOD
    #define RGBLIGHT_EFFECT_RAINBOW_SWIRL
#endif

//Стандартный режим мыши(ускоренный)
//#define MOUSEKEY_DELAY		0
//#define MOUSEKEY_INTERVAL	16
//#define MOUSEKEY_MAX_SPEED 2
//#define MOUSEKEY_TIME_TO_MAX 50

//  Кинетический режим мыши
//#define MK_KINETIC_SPEED
//#define MOUSEKEY_WHEEL_INITIAL_MOVEMENTS	2
//#define MOUSEKEY_MOVE_DELTA 10


// Энерция мыши
#define MOUSEKEY_INERTIA
#define MOUSEKEY_DELAY 200
#define MOUSEKEY_INTERVAL  16
#define MOUSEKEY_MAX_SPEED  20
#define MOUSEKEY_TIME_TO_MAX  40
#define MOUSEKEY_FRICTION  12
#define MOUSEKEY_MOVE_DELTA  1