BOARD = GENERIC_RP_RP2040

VIA_ENABLE = no
WPM_ENABLE = yes
LEADER_ENABLE = yes
DYNAMIC_MACRO_ENABLE = yes
KEY_OVERRIDE_ENABLE = yes

# AUDIO
AUDIO_ENABLE = yes
AUDIO_DRIVER = pwm_hardware

#EEPROM_DRIVER = transient

#UNICODE_ENABLE = yes
#UNICODEMAP_ENABLE = yes

#Display
OLED_ENABLE = yes
OLED_DRIVER = ssd1306 # OLED SSD1306 128x32
OLED_TRANSPORT = i2c

//OPT_DEFS += -DHAL_USE_I2C=TRUE
//SRC += analog.c

# WS2812 RGB LED
RGBLIGHT_ENABLE = yes
WS2812_DRIVER = vendor
#WS2812_DRIVER = pwm #bitbang

BACKLIGHT_ENABLE = no
